import Head from 'next/head'
import { Box, SimpleGrid } from '@chakra-ui/react'

export default function Home() {
  const colors = []
  for (let color of ['Primary', 'Neutral', 'Success', 'Error', 'Warning']) {
    for (let number of [20,30,40,50,60,70,80,90]) {
      colors.push(`Palette.${color}.${number}`)
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box bgColor="red.100">I am red.100 (Chakra default)</Box>
        <Box bgColor="Palette.Primary.50">I am Palette/Primary/50</Box>
        <Box bgColor="Color.Container.Primary.Interactive.Enable">I am Color/Container/Primary/Interactive/Enable</Box>

      <SimpleGrid w="700px" columns="8" spacing="8px">
        {
          colors.map(name => {
            const figmaName = name.replaceAll('.','/');
            return <Box key={name} fontSize="12px" bgColor={name} h="80px" w="80px" >{figmaName}</Box>
          })
        }
        </SimpleGrid>
      </main>
    </>
  )
}
